[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "pyexample"
authors = [{name = "yapingxin", email = "yapingxin@gmail.com"}]
dynamic = ["version", "description"]
